### ISSUE TITLE
I just installed with misquitto mqtt on home assistant and get the following error when I try to start blueti-mqtt

### ISSUE THREAD

**Issue by ceredoandy** [warhammerkid/bluetti_mqtt#107]
We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. 
2024-03-14 13:50:27 INFO     Connecting to MQTT broker...
Exception ignored in: <function Client.__del__ at 0x0000023170937100>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\paho\mqtt\client.py", line 874, in __del__
    self._reset_sockets()
  File "C:\Program Files\Python312\Lib\site-packages\paho\mqtt\client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "C:\Program Files\Python312\Lib\site-packages\paho\mqtt\client.py", line 1119, in _sock_close
    if not self._sock:
           ^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_sock'
2024-03-14 13:50:27 INFO     Starting to poll clients...
2024-03-14 13:50:27 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\site-packages\bluetti_mqtt\mqtt_client.py", line 513, in run
    async with Client(
               ^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\asyncio_mqtt\client.py", line 298, in __init__
    self._client: mqtt.Client = mqtt.Client(
                                ^^^^^^^^^^^^
TypeError: Client.__init__() missing 1 required positional argument: 'callback_api_version'
2024-03-14 13:50:27 INFO     Connecting to clients: ['70:B8:F6:81:A7:66']
2024-03-14 13:50:27 INFO     Shutting down...

**Comment by shbatm** [comment]
Seeing the same issue connecting to Home Assistant Addon.

Seems like it's related to: https://github.com/eclipse/paho.mqtt.python/issues/814

**Comment by chaoszone** [comment]
Has anyone found a fix yet?

**Comment by shbatm** [comment]
Working with my Pull Request here if you want to use that version for now:

https://github.com/warhammerkid/bluetti_mqtt/pull/108

**Comment by chaoszone** [comment]
How do I get your version into my HA instance?

**Comment by ftrueck** [comment]
I am currently preparing of creating a separate addon and a separate github fork for a more updated version of the underlying library. Not sure how long it will take until I am done but I have the same Issues as you guys and I am kind of tired waiting for the original maintainers to wake up from their winter sleep.
