### ISSUE TITLE
Support for AC180

### ISSUE THREAD

**Issue by mjnovotny82** [warhammerkid/bluetti_mqtt#112]
Running this with HA using ae139cbc_bluetti2mqtt

```
-----------------------------------------------------------
 Add-on: Bluetti to MQTT
 MQTT bridge between Bluetti and Home Assistant
-----------------------------------------------------------
 Add-on version: 1.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.2  (aarch64 / yellow)
 Home Assistant Core: 2024.4.4
 Home Assistant Supervisor: 2024.04.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[17:11:00] INFO: Reading configuration settings...
[17:11:03] INFO: Starting bluetti-mqtt...
2024-05-04 17:11:05 INFO     Connecting to MQTT broker...
2024-05-04 17:11:05 INFO     Starting to poll clients...
2024-05-04 17:11:05 INFO     Connecting to clients: ['FB:86:44:00:00:00']
2024-05-04 17:11:05 INFO     Connected to MQTT broker
2024-05-04 17:11:05 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
2024-05-04 17:11:13 INFO     Connected to device: FB:86:44:00:00:00
2024-05-04 17:11:13 INFO     Device FB:86:44:00:00:00 has name: AC1802409001111111
2024-05-04 17:11:13 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 31, in run
    await asyncio.gather(*(polling_tasks + pack_polling_tasks + [manager_task]))
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 45, in _poll
    device = self._get_device(address)
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 103, in _get_device
    self.devices[address] = build_device(address, name)
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/bluetooth/__init__.py", line 28, in build_device
    if match[1] == 'AC200M':
TypeError: 'NoneType' object is not subscriptable
2024-05-04 17:11:13 INFO     Shutting down...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
.

**Comment by mjnovotny82** [comment]
Appears to be a dup with https://github.com/warhammerkid/bluetti_mqtt/issues/84

**Comment by mjnovotny82** [comment]
https://github.com/warhammerkid/bluetti_mqtt/issues/84
