### ISSUE TITLE
Can't connect device

### ISSUE THREAD

**Issue by shurubura** [warhammerkid/bluetti_mqtt#117]
bluetti-mqtt --broker localhost --interval 10 6C9D629C-8755-D05B-FC20-3802D7F0F97B

We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt
2024-07-17 13:43:33 INFO     Connecting to MQTT broker...
2024-07-17 13:43:33 INFO     Starting to poll clients...
2024-07-17 13:43:33 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/Users/kostantinsurubura/bluetti_env/lib/python3.12/site-packages/bluetti_mqtt/mqtt_client.py", line 513, in run
    async with Client(
               ^^^^^^^
  File "/Users/kostantinsurubura/bluetti_env/lib/python3.12/site-packages/asyncio_mqtt/client.py", line 349, in __init__
    self._client.message_retry_set(message_retry_set)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'message_retry_set'
2024-07-17 13:43:33 INFO     Connecting to clients: ['6C9D629C-8755-D05B-FC20-3802D7F0F97B']
2024-07-17 13:43:33 INFO     Shutting down...

**Comment by mpapirkovskyy** [comment]
You need to downgrade paho-mqtt library, there were breaking changes there
`pip install paho-mqtt==1.6.1`
