### ISSUE TITLE
Constant timeout errors with the mqtt client

### ISSUE THREAD

**Issue by bobthebuilder4711** [warhammerkid/bluetti_mqtt#85]
Hi,

I've got bluetti_mqtt running on a Raspberry Pi 1 B+ with a usb wifi and a usb bluetooth dongle.

In the past it used to work sort of fine. Once in a while I could see in home assistant (running on another server in a VM) that the values wouldn't come in each second (I start the program with that interval set) but more like a rapid fire of 2 values and then 1-2 seconds nothing and then another rapid fire and so on. For that I simply added a cron that runs every 6 hours and restarts the service and that seemed to work good enough.

Now I've started using the "Battery Range Start" slider to make my AC500 stop charging during the night instead of unplugging it every evening when the sun goes down. That has led to the rapid fire becoming a lot more common.

And once the rapid fire behaviour starts, I can adjust fields of the AC500 via the Home Assistant gui and the AC500 will adopt these changes, but I don't get a confirmation back, so if I adjust the "Battery Range Start" from 100% to 50% then the AC500 will set it to 50%, but when I reload the gui of Home Assistant, it shows 100% again. And things like the total battery percentage will not update until I've restarted the service.

I've updated Home Assistant to the newest version and that way the built in MQTT broker was updated as well. And then I've used "pip3 install <url to tar ball of version 0.15.0>" to install the latest release of bluetti_mqtt.

And now I'm constantly seeing these errors (log is since the last systemctl restart):
```
Jul 19 11:40:47 raspberrypi systemd[1]: Stopping Bluetti MQTT...
Jul 19 11:40:47 raspberrypi systemd[1]: bluetti-mqtt.service: Main process exited, code=killed, status=15/TERM
Jul 19 11:40:47 raspberrypi ac500.sh[356]: 2023-07-19 11:40:47 INFO     Shutting down...
Jul 19 11:40:47 raspberrypi ac500.sh[356]: 2023-07-19 11:40:47 INFO     Shutting down...
Jul 19 11:40:48 raspberrypi systemd[1]: bluetti-mqtt.service: Succeeded.
Jul 19 11:40:48 raspberrypi systemd[1]: Stopped Bluetti MQTT.
Jul 19 11:40:48 raspberrypi systemd[1]: Started Bluetti MQTT.
Jul 19 11:40:53 raspberrypi ac500.sh[574]: 2023-07-19 11:40:53 INFO     Connecting to MQTT broker...
Jul 19 11:40:53 raspberrypi ac500.sh[574]: 2023-07-19 11:40:53 INFO     Starting to poll clients...
Jul 19 11:40:53 raspberrypi ac500.sh[574]: 2023-07-19 11:40:53 INFO     Connecting to clients: ['24:4C:AB:2E:21:76']
Jul 19 11:40:54 raspberrypi ac500.sh[574]: 2023-07-19 11:40:54 INFO     Connected to MQTT broker
Jul 19 11:40:55 raspberrypi ac500.sh[574]: 2023-07-19 11:40:55 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 11:41:02 raspberrypi ac500.sh[574]: 2023-07-19 11:41:02 INFO     Connected to device: 24:4C:AB:2E:21:76
Jul 19 11:41:02 raspberrypi ac500.sh[574]: 2023-07-19 11:41:02 INFO     Device 24:4C:AB:2E:21:76 has name: AC5002242000779423
Jul 19 11:41:03 raspberrypi ac500.sh[574]: 2023-07-19 11:41:03 INFO     Sent discovery message of AC500-2242000779423 to Home Assistant
Jul 19 12:25:03 raspberrypi ac500.sh[574]: 2023-07-19 12:25:03 ERROR    MQTT error:
Jul 19 12:25:03 raspberrypi ac500.sh[574]: Traceback (most recent call last):
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     self._handle_messages(client)
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     await self._handle_message(client, msg)
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     return await method(self, *args, **kwargs)
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 12:25:03 raspberrypi ac500.sh[574]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 12:25:03 raspberrypi ac500.sh[574]:     raise MqttError("Operation timed out") from None
Jul 19 12:25:03 raspberrypi ac500.sh[574]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 12:25:08 raspberrypi ac500.sh[574]: 2023-07-19 12:25:08 INFO     Connecting to MQTT broker...
Jul 19 12:25:09 raspberrypi ac500.sh[574]: 2023-07-19 12:25:09 INFO     Connected to MQTT broker
Jul 19 12:25:09 raspberrypi ac500.sh[574]: 2023-07-19 12:25:09 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
```

I'm writing this 40 minutes later. No further log entries, but the rapid fire status updates in Home Assistant are there again and I can only get it back to working normally by restarting the service.

**Comment by bobthebuilder4711** [comment]
I restartet 2 hours ago after I made the initial post and since then this has happened (including the last line from the last log):

```
Jul 19 12:25:09 raspberrypi ac500.sh[574]: 2023-07-19 12:25:09 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 13:08:01 raspberrypi systemd[1]: Stopping Bluetti MQTT...
Jul 19 13:08:01 raspberrypi ac500.sh[574]: 2023-07-19 13:08:01 INFO     Shutting down...
Jul 19 13:08:01 raspberrypi systemd[1]: bluetti-mqtt.service: Main process exited, code=killed, status=15/TERM
Jul 19 13:08:02 raspberrypi ac500.sh[574]: 2023-07-19 13:08:02 INFO     Shutting down...
Jul 19 13:08:02 raspberrypi systemd[1]: bluetti-mqtt.service: Succeeded.
Jul 19 13:08:02 raspberrypi systemd[1]: Stopped Bluetti MQTT.
Jul 19 13:08:02 raspberrypi systemd[1]: Started Bluetti MQTT.
Jul 19 13:08:08 raspberrypi ac500.sh[650]: 2023-07-19 13:08:08 INFO     Connecting to MQTT broker...
Jul 19 13:08:08 raspberrypi ac500.sh[650]: 2023-07-19 13:08:08 INFO     Starting to poll clients...
Jul 19 13:08:08 raspberrypi ac500.sh[650]: 2023-07-19 13:08:08 INFO     Connecting to clients: ['24:4C:AB:2E:21:76']
Jul 19 13:08:10 raspberrypi ac500.sh[650]: 2023-07-19 13:08:10 INFO     Connected to MQTT broker
Jul 19 13:08:10 raspberrypi ac500.sh[650]: 2023-07-19 13:08:10 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 13:08:17 raspberrypi ac500.sh[650]: 2023-07-19 13:08:17 INFO     Connected to device: 24:4C:AB:2E:21:76
Jul 19 13:08:17 raspberrypi ac500.sh[650]: 2023-07-19 13:08:17 INFO     Device 24:4C:AB:2E:21:76 has name: AC5002242000779423
Jul 19 13:08:18 raspberrypi ac500.sh[650]: 2023-07-19 13:08:18 INFO     Sent discovery message of AC500-2242000779423 to Home Assistant
Jul 19 13:52:17 raspberrypi ac500.sh[650]: 2023-07-19 13:52:17 WARNING  Could not gracefully disconnect due to "Operation timed out". Forcing disconnection.
Jul 19 13:52:17 raspberrypi ac500.sh[650]: 2023-07-19 13:52:17 ERROR    MQTT error:
Jul 19 13:52:17 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 13:52:17 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 13:52:17 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 13:52:17 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 13:52:22 raspberrypi ac500.sh[650]: 2023-07-19 13:52:22 INFO     Connecting to MQTT broker...
Jul 19 13:52:22 raspberrypi ac500.sh[650]: 2023-07-19 13:52:22 INFO     Connected to MQTT broker
Jul 19 13:52:22 raspberrypi ac500.sh[650]: 2023-07-19 13:52:22 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 14:39:37 raspberrypi ac500.sh[650]: 2023-07-19 14:39:37 ERROR    MQTT error:
Jul 19 14:39:37 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 14:39:37 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 14:39:37 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 14:39:37 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 14:39:42 raspberrypi ac500.sh[650]: 2023-07-19 14:39:42 INFO     Connecting to MQTT broker...
Jul 19 14:39:42 raspberrypi ac500.sh[650]: 2023-07-19 14:39:42 INFO     Connected to MQTT broker
Jul 19 14:39:42 raspberrypi ac500.sh[650]: 2023-07-19 14:39:42 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 14:40:21 raspberrypi ac500.sh[650]: 2023-07-19 14:40:21 ERROR    MQTT error:
Jul 19 14:40:21 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 14:40:21 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 14:40:21 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 14:40:21 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 14:40:26 raspberrypi ac500.sh[650]: 2023-07-19 14:40:26 INFO     Connecting to MQTT broker...
Jul 19 14:40:26 raspberrypi ac500.sh[650]: 2023-07-19 14:40:26 INFO     Connected to MQTT broker
Jul 19 14:40:26 raspberrypi ac500.sh[650]: 2023-07-19 14:40:26 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 14:42:32 raspberrypi ac500.sh[650]: 2023-07-19 14:42:32 ERROR    MQTT error:
Jul 19 14:42:32 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 14:42:32 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 14:42:32 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 14:42:32 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 14:42:37 raspberrypi ac500.sh[650]: 2023-07-19 14:42:37 INFO     Connecting to MQTT broker...
Jul 19 14:42:37 raspberrypi ac500.sh[650]: 2023-07-19 14:42:37 INFO     Connected to MQTT broker
Jul 19 14:42:37 raspberrypi ac500.sh[650]: 2023-07-19 14:42:37 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 14:59:46 raspberrypi ac500.sh[650]: 2023-07-19 14:59:46 ERROR    MQTT error:
Jul 19 14:59:46 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 14:59:46 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 14:59:46 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 14:59:46 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 14:59:51 raspberrypi ac500.sh[650]: 2023-07-19 14:59:51 INFO     Connecting to MQTT broker...
Jul 19 14:59:52 raspberrypi ac500.sh[650]: 2023-07-19 14:59:52 INFO     Connected to MQTT broker
Jul 19 14:59:52 raspberrypi ac500.sh[650]: 2023-07-19 14:59:52 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
Jul 19 15:29:53 raspberrypi ac500.sh[650]: 2023-07-19 15:29:53 WARNING  Could not gracefully disconnect due to "Operation timed out". Forcing disconnection.
Jul 19 15:29:53 raspberrypi ac500.sh[650]: 2023-07-19 15:29:53 ERROR    MQTT error:
Jul 19 15:29:53 raspberrypi ac500.sh[650]: Traceback (most recent call last):
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 528, in run
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     self._handle_messages(client)
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 548, in _handle_messages
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     await self._handle_message(client, msg)
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/bluetti_mqtt/mqtt_client.py", line 692, in _handle_message
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     await client.publish(topic_prefix + name, payload=payload.encode())
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     return await method(self, *args, **kwargs)
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 474, in publish
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     await self._wait_for(confirmation.wait(), timeout=timeout)
Jul 19 15:29:53 raspberrypi ac500.sh[650]:   File "/usr/local/lib/python3.7/dist-packages/asyncio_mqtt/client.py", line 636, in _wait_for
Jul 19 15:29:53 raspberrypi ac500.sh[650]:     raise MqttError("Operation timed out") from None
Jul 19 15:29:53 raspberrypi ac500.sh[650]: asyncio_mqtt.error.MqttError: Operation timed out
Jul 19 15:29:58 raspberrypi ac500.sh[650]: 2023-07-19 15:29:58 INFO     Connecting to MQTT broker...
Jul 19 15:29:59 raspberrypi ac500.sh[650]: 2023-07-19 15:29:59 INFO     Connected to MQTT broker
Jul 19 15:29:59 raspberrypi ac500.sh[650]: 2023-07-19 15:29:59 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
```

**Comment by bobthebuilder4711** [comment]
I've found the problem. The raspberry pi was generally accessible via SSH, so it never really occurred to me that the wifi connection might be the problem. But turns out that the access point closest to the raspberry pi got unplugged and the next access point was too far away and too many packages got dropped.

No more exceptions since the access point got plugged in again.
