### ISSUE TITLE
PB home assistant + bluettitomqtt 

### ISSUE THREAD

**Issue by DocG2** [warhammerkid/bluetti_mqtt#88]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: Bluetti to MQTT
 MQTT bridge between Bluetti and Home Assistant
-----------------------------------------------------------
 Add-on version: 1.4.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.1
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:00:58] INFO: Reading configuration settings...
[20:00:59] INFO: Starting bluetti-mqtt...
2023-09-10 20:01:00 INFO     Connecting to MQTT broker...
2023-09-10 20:01:00 INFO     Starting to poll clients...
2023-09-10 20:01:00 INFO     Connecting to clients: ['DC:13:7C:3A:D7:C0']
2023-09-10 20:01:00 INFO     Connected to MQTT broker
2023-09-10 20:01:00 WARNING  filtered_messages() is deprecated and will be removed in a future version. Use messages() together with Topic.matches() instead.
2023-09-10 20:01:00 ERROR    Crashing with uncaught exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/device_handler.py", line 31, in run
    await asyncio.gather(*(polling_tasks + pack_polling_tasks + [manager_task]))
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/bluetooth/manager.py", line 20, in run
    await BleakScanner.discover()
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 242, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 152, in __aenter__
    await self._backend.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 191, in start
    self._stop = await manager.active_scan(
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/manager.py", line 368, in active_scan
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 22, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.InProgress] Operation already in progress
2023-09-10 20:01:00 INFO     Shutting down...
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Patrick762** [comment]
Seems like this issue should go here https://github.com/SSMCD/bluetti2mqtt/issues
