### ISSUE TITLE
bluetti-mqtt HAOS add-on no longer working after latest upgrade 

### ISSUE THREAD

**Issue by GHJJ123** [warhammerkid/bluetti_mqtt#95]
`Core
2024.1.3
Supervisor
2023.12.0
Operating System
11.4
Frontend
20240104.0`

I've been encountering this error since I upgrade HAOS to the latest version. I'm assuming this has to do with python 3.10 package? Since there was no update on bluetti_mqtt add-on since 05/2023. 

Checking the directory /usr/local/lib/ there is nothing there except /perl5 and [which python3.10] gives me not found.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bluetti_mqtt/bluetooth/client.py", line 78, in _connect
    await self.client.connect()
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 531, in connect
    return await self._backend.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 141, in connect
    async with async_timeout(timeout):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2024-01-15 10:06:38 ERROR    Error connecting to device 05:8F:0E:AD:2B:5D:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 204, in connect
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 371, in call
    await future
asyncio.exceptions.CancelledError`

Any help appreciated, thank you!

I've posted this in the add-on git as well. Wasn't sure which git would be able to resolve.
https://github.com/SSMCD/bluetti2mqtt

**Comment by GHJJ123** [comment]
closed, looks like there was a connection issue lol.
